spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flats_chooser
    password: 12345678
    username: postgres
  mail:
    host: smtp.google.com
    port: 587
    username: radyuknikita02@gmail.com
    password: gddxhemucvuzkpap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy
  feign:
    audit-logs:
      url: http://audit-service:8084

custom:
  mail:
    message: |
      Чтобы пройти верификацию, перейдите по ссылке:
      http://localhost:8080/users/verification?mail=%s&code=%s
